<?php

return [
    "illuminate/html" => [
        "Html/HtmlBuilder",
        "Html/FormBuilder",
    ],
    "orchestra/asset" => [
        "Asset/AssetServiceProvider",
        "Asset/Asset",
        "Asset/DependencyResolver",
        "Asset/Dispatcher",
        "Asset/Factory",
    ],
    "orchestra/auth" => [
        "Auth/AuthManager",
        "Auth/Guard",
        "Auth/Acl/AuthorizationTrait",
        "Auth/Acl/Acl",
        "Auth/Acl/Factory",
        "Auth/Acl/Fluent",
    ],
    "orchestra/debug" => [
        "Debug/DebugServiceProvider",
        "Debug/Traits/MonologTrait",
        "Debug/Traits/TimerProfileTrait",
        "Debug/Listener",
        "Debug/Profiler",
    ],
    "orchestra/extension" => [
        "Extension/Traits/DispatchableTrait",
        "Extension/Traits/OperationTrait",
        "Extension/ConfigManager",
        "Extension/Dispatcher",
        "Extension/Factory",
        "Extension/ProviderRepository",
        "Extension/RouteGenerator",
        "Extension/SafeModeChecker",
    ],
    "orchestra/facile" => [
        "Facile/FacileServiceProvider",
        "Facile/Facile",
        "Facile/Factory",
        "Facile/Transformable",
        "Facile/Template/Template",
        "Facile/Template/Simple",
    ],
    "orchestra/foundation" => [
        "Foundation/SupportServiceProvider",
        "Foundation/Application",
        "Foundation/Foundation",
        "Foundation/Meta",
    ],
    "orchestra/html" => [
        "Html/HtmlBuilder",
        "Html/FormBuilder",
        "Html/Builder",
        "Html/Factory",
        "Html/Grid",
        "Html/Form/Control",
        "Html/Form/Factory",
        "Html/Form/Field",
        "Html/Form/Fieldset",
        "Html/Form/FormBuilder",
        "Html/Form/Grid",
        "Html/Table/Column",
        "Html/Table/Factory",
        "Html/Table/Grid",
        "Html/Table/TableBuilder",
    ],
    "orchestra/kernel" => [
        "Contracts/Support/DataContainer",
        "Contracts/Memory/Handler",
        "Contracts/Memory/Provider",
        "Contracts/Extension/Dispatcher",
        "Contracts/Extension/Factory",
        "Contracts/Extension/RouteGenerator",
        "Contracts/Extension/SafeMode",
        "Contracts/Foundation/DeferrableServiceContainer",
        "Contracts/Foundation/Foundation",
        "Contracts/Html/Factory",
        "Contracts/Html/Builder",
        "Contracts/Html/Grid",
        "Contracts/Html/Form/Factory",
        "Contracts/Html/Form/Builder",
        "Contracts/Html/Form/Grid",
        "Contracts/Html/Form/Control",
        "Contracts/Html/Form/Presenter",
        "Contracts/Html/Table/Factory",
        "Contracts/Html/Table/Builder",
        "Contracts/Html/Table/Grid",
        "Contracts/Http/RouteManager",
        "Contracts/Messages/MessageBag",
        "Contracts/Notification/Message",
        "Contracts/Notification/Notification",
        "Contracts/Notification/Receipt",
        "Contracts/Notification/Recipient",
        "Contracts/View/Theme/Theme",
        "Contracts/View/Theme/Finder",
        "Http/FormRequest",
        "Http/RouteManager",
    ],
    "orchestra/memory" => [
        "Memory/MemoryManager",
        "Memory/Provider",
        "Memory/ContainerTrait",
        "Memory/Handler",
        "Memory/Handlers/Cache",
        "Memory/Handlers/Eloquent",
        "Memory/Handlers/Fluent",
        "Memory/Handlers/Runtime",
    ],
    "orchestra/model" => [
        "Model/Observer/Role",
        "Model/Memory/UserMetaProvider",
        "Model/Memory/UserMetaRepository",
    ],
    "orchestra/messages" => [
        "Messages/MessagesServiceProvider",
        "Messages/MessageBag",
    ],
    "orchestra/notifier" => [
        "Notifier/NotifierServiceProvider",
        "Notifier/NotifiableTrait",
        "Notifier/Receipt",
    ],
    "orchestra/resources" => [
        "Resources/ResourcesServiceProvider",
        "Resources/Router",
        "Resources/Dispatcher",
        "Resources/Factory",
        "Resources/Resolver",
        "Resources/Response",
        "Resources/Routing/ControllerDispatcher",
        "Resources/Routing/Route",
    ],
    "orchestra/support" => [
        "Providers/Traits/AliasesProviderTrait",
        "Providers/ServiceProvider",
        "Providers/FilterServiceProvider",
        "Support/Contracts/CsvableInterface",
        "Support/Traits/ControllerResponseTrait",
        "Support/Traits/DataContainerTrait",
        "Support/Traits/DescendibleTrait",
        "Support/Traits/QueryFilterTrait",
        "Support/Traits/ValidationTrait",
        "Support/Collection",
        "Support/Expression",
        "Support/Manager",
        "Support/Nesty",
        "Support/Str",
        "Support/Validator",
        "Facades/ACL",
        "Facades/Asset",
        "Facades/Config",
        "Facades/Decorator",
        "Facades/Facile",
        "Facades/Form",
        "Facades/Foundation",
        "Facades/HTML",
        "Facades/Mail",
        "Facades/Memory",
        "Facades/Messages",
        "Facades/Meta",
        "Facades/Profiler",
        "Facades/Publisher",
        "Facades/Resources",
        "Facades/Table",
        "Facades/Theme",
        "Facades/Widget",
    ],
    "orchestra/translation" => [
        "Translation/TranslationServiceProvider",
        "Translation/FileLoader",
    ],
    "orchestra/view" => [
        "View/ViewServiceProvider",
        "View/DecoratorServiceProvider",
        "View/Decorator",
        "View/FileViewFinder",
        "View/Theme/Theme",
        "View/Theme/Finder",
        "View/Theme/Manifest",
        "View/Theme/ThemeManager",
    ],
    "orchestra/widget" => [
        "Widget/WidgetManager",
        "Widget/Handler",
        "Widget/Handlers/Menu",
        "Widget/Handlers/Pane",
        "Widget/Handlers/Placeholder",
    ],
];
