<?php

return [
    "illuminate/html" => [
        "HtmlBuilder",
        "FormBuilder",
    ],
    "orchestra/asset" => [
        "src/Asset/AssetServiceProvider",
        "src/Asset/Asset",
        "src/Asset/DependencyResolver",
        "src/Asset/Dispatcher",
        "src/Asset/Factory",
    ],
    "orchestra/auth" => [
        "src/Auth/AuthManager",
        "src/Auth/Guard",
        "src/Authorization/AuthorizationTrait",
        "src/Authorization/Authorization",
        "src/Authorization/Factory",
        "src/Authorization/Fluent",
    ],
    "orchestra/debug" => [
        "src/Debug/DebugServiceProvider",
        "src/Debug/Traits/MonologTrait",
        "src/Debug/Traits/TimerProfileTrait",
        "src/Debug/Listener",
        "src/Debug/Profiler",
    ],
    "orchestra/extension" => [
        "src/Extension/Traits/DispatchableTrait",
        "src/Extension/Traits/OperationTrait",
        "src/Extension/Config/Repository",
        "src/Extension/Dispatcher",
        "src/Extension/Factory",
        "src/Extension/ProviderRepository",
        "src/Extension/RouteGenerator",
        "src/Extension/SafeModeChecker",
    ],
    "orchestra/facile" => [
        "src/Facile/FacileServiceProvider",
        "src/Facile/Facile",
        "src/Facile/Factory",
        "src/Facile/Transformable",
        "src/Facile/Template/Template",
        "src/Facile/Template/Simple",
    ],
    "orchestra/foundation" => [
        "src/Foundation/Providers/SupportServiceProvider",
        "src/Foundation/Application",
        "src/Foundation/Foundation",
        "src/Foundation/Meta",
    ],
    "orchestra/html" => [
        "src/Html/HtmlBuilder",
        "src/Html/FormBuilder",
        "src/Html/Builder",
        "src/Html/Factory",
        "src/Html/Grid",
        "src/Html/Form/Control",
        "src/Html/Form/Factory",
        "src/Html/Form/Field",
        "src/Html/Form/Fieldset",
        "src/Html/Form/FormBuilder",
        "src/Html/Form/Grid",
        "src/Html/Table/Column",
        "src/Html/Table/Factory",
        "src/Html/Table/Grid",
        "src/Html/Table/TableBuilder",
    ],
    "orchestra/kernel" => [
        "src/Contracts/Support/DataContainer",
        "src/Contracts/Memory/Handler",
        "src/Contracts/Memory/Provider",
        "src/Contracts/Extension/Dispatcher",
        "src/Contracts/Extension/Factory",
        "src/Contracts/Extension/RouteGenerator",
        "src/Contracts/Extension/SafeMode",
        "src/Contracts/Foundation/DeferrableServiceContainer",
        "src/Contracts/Foundation/Foundation",
        "src/Contracts/Html/Factory",
        "src/Contracts/Html/Builder",
        "src/Contracts/Html/Grid",
        "src/Contracts/Html/Form/Factory",
        "src/Contracts/Html/Form/Builder",
        "src/Contracts/Html/Form/Grid",
        "src/Contracts/Html/Form/Control",
        "src/Contracts/Html/Form/Presenter",
        "src/Contracts/Html/Table/Factory",
        "src/Contracts/Html/Table/Builder",
        "src/Contracts/Html/Table/Grid",
        "src/Contracts/Http/RouteManager",
        "src/Contracts/Messages/MessageBag",
        "src/Contracts/Notification/Message",
        "src/Contracts/Notification/Notification",
        "src/Contracts/Notification/Receipt",
        "src/Contracts/Notification/Recipient",
        "src/Contracts/Theme/Theme",
        "src/Contracts/Theme/Finder",
        "src/Http/FormRequest",
        "src/Http/RouteManager",
        "src/Routing/Router",
        "src/Routing/ControllerDispatcher",
        "src/Routing/Controller",
        "src/Routing/Traits/ControllerResponseTrait",
    ],
    "orchestra/memory" => [
        "src/Memory/MemoryManager",
        "src/Memory/Provider",
        "src/Memory/ContainerTrait",
        "src/Memory/Handler",
        "src/Memory/Handlers/Cache",
        "src/Memory/Handlers/Eloquent",
        "src/Memory/Handlers/Fluent",
        "src/Memory/Handlers/Runtime",
    ],
    "orchestra/model" => [
        "src/Model/Observer/Role",
        "src/Model/Memory/UserMetaProvider",
        "src/Model/Memory/UserMetaRepository",
    ],
    "orchestra/messages" => [
        "src/Messages/MessagesServiceProvider",
        "src/Messages/MessageBag",
    ],
    "orchestra/notifier" => [
        "src/Notifier/NotifierServiceProvider",
        "src/Notifier/NotifiableTrait",
        "src/Notifier/Receipt",
    ],
    "orchestra/resources" => [
        "src/Resources/ResourcesServiceProvider",
        "src/Resources/Router",
        "src/Resources/Dispatcher",
        "src/Resources/Factory",
        "src/Resources/Resolver",
        "src/Resources/Response",
        "src/Resources/Routing/ControllerDispatcher",
        "src/Resources/Routing/Route",
    ],
    "orchestra/support" => [
        "src/Providers/Traits/AliasesProviderTrait",
        "src/Providers/ServiceProvider",
        "src/Providers/FilterServiceProvider",
        "src/Support/Contracts/CsvableInterface",
        "src/Support/Traits/DataContainerTrait",
        "src/Support/Traits/DescendibleTrait",
        "src/Support/Traits/QueryFilterTrait",
        "src/Support/Traits/ValidationTrait",
        "src/Support/Collection",
        "src/Support/Expression",
        "src/Support/Manager",
        "src/Support/Nesty",
        "src/Support/Str",
        "src/Support/Validator",
        "src/Facades/ACL",
        "src/Facades/Asset",
        "src/Facades/Config",
        "src/Facades/Decorator",
        "src/Facades/Facile",
        "src/Facades/Form",
        "src/Facades/Foundation",
        "src/Facades/HTML",
        "src/Facades/Mail",
        "src/Facades/Memory",
        "src/Facades/Messages",
        "src/Facades/Meta",
        "src/Facades/Profiler",
        "src/Facades/Publisher",
        "src/Facades/Resources",
        "src/Facades/Table",
        "src/Facades/Theme",
        "src/Facades/Widget",
    ],
    "orchestra/translation" => [
        "src/Translation/TranslationServiceProvider",
        "src/Translation/FileLoader",
    ],
    "orchestra/view" => [
        "src/View/ViewServiceProvider",
        "src/View/DecoratorServiceProvider",
        "src/View/Decorator",
        "src/View/FileViewFinder",
        "src/View/Theme/Theme",
        "src/View/Theme/Finder",
        "src/View/Theme/Manifest",
        "src/View/Theme/ThemeManager",
    ],
    "orchestra/widget" => [
        "src/Widget/WidgetManager",
        "src/Widget/Handler",
        "src/Widget/Handlers/Menu",
        "src/Widget/Handlers/Pane",
        "src/Widget/Handlers/Placeholder",
    ],
];
